CREATE TABLE `tf_campaign` (
  `CAMPAIGN_ID` char(20) NOT NULL DEFAULT '' COMMENT '活动ID',
  `CAMPAIGN_CODE` varchar(12) NOT NULL COMMENT '活动编号，系统编号格式{6位年月日}C(2位活动类型编码){3位序号}，允许自定义编号，不超过12位',
  `CAMPAIGN_TYPE` char(2) NOT NULL COMMENT '活动类型，对应系统参数表',
  `CAMPAIGN_NAME` varchar(100) NOT NULL COMMENT '活动名称',
  `CAMPAIGN_STATE` char(1) NOT NULL COMMENT '活动状态：0待发布、1已发布、2已暂停、9已终止',
  `CAMPAIGN_URL_ID` char(25) NOT NULL,
  `TIME_START` datetime NOT NULL COMMENT '活动开始时间',
  `TIME_END` datetime NOT NULL COMMENT '活动结束时间',
  `ORIGINAL_PRICE` int(11) NOT NULL DEFAULT '0' COMMENT '活动卡券合计原价，单位：分',
  `PROMOTION_PRICE` int(11) NOT NULL DEFAULT '0' COMMENT '活动卡券合计优惠价格（实际销售的价格），单位：分',
  `AMOUNT_INVENTORY` int(11) NOT NULL DEFAULT '0' COMMENT '库存数量（份数/拼团数），默认1，订单完成时减少',
  `AMOUNT_SELL` int(11) NOT NULL DEFAULT '0' COMMENT '已售数量（份数/拼团数），默认0，订单完成时增加',
  `CAMPNAVI_SHOW_FLAGS` char(1) NOT NULL DEFAULT '1' COMMENT '在优惠活动导航页展示：0不展示/隐藏、1展示，默认1',
  `ANONYMOUS_VIEW` char(1) NOT NULL DEFAULT '1' COMMENT '匿名访问：0 不允许，1 允许',
  `LAYOUT_CODE` char(6) NOT NULL COMMENT '活动页版式编码',
  `PAGE_COUNT` int(11) NOT NULL DEFAULT '1' COMMENT '包含的页面数，默认1',
  `PAGE_TITLE` varchar(60) NOT NULL COMMENT '活动页标题，默认活动名称',
  `SHARE_TITLE` varchar(100) NOT NULL COMMENT '分享标题，默认活动名称',
  `SHARE_SUMMARY` varchar(150) NOT NULL COMMENT '分享摘要',
  `SHARE_ICON_URL` varchar(256) DEFAULT NULL COMMENT '分享图标URL，默认商户LOGO',
  `SHARE_TITLE_DONE` varchar(100) DEFAULT NULL COMMENT '参与了活动的分享标题',
  `SHARE_SUMMARY_DONE` varchar(150) DEFAULT NULL COMMENT '参与了活动的分享摘要',
  `BANNER_IMGURL` varchar(256) DEFAULT NULL COMMENT '活动封面图URL，默认使用活动页的Banner图片',
  `BG_COLOR` varchar(20) DEFAULT NULL COMMENT '背景颜色',
  `LAST_RELEASE_TIME` datetime DEFAULT NULL COMMENT '最近发布成功时间，仅状态为0时可空',
  `OPERATOR_MEMO` varchar(1000) DEFAULT NULL COMMENT '操作人备注',
  `OPERATOR_ID` char(20) NOT NULL COMMENT '操作人ID',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '更新时间',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '系统备注',
  `CAMPAIGN_CLOSE_REASON` varchar(200) DEFAULT NULL COMMENT '活动关闭原因',
  PRIMARY KEY (`CAMPAIGN_ID`),
  UNIQUE KEY `IDX_CAMPAIGN_CODE` (`CAMPAIGN_CODE`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动主表';

CREATE TABLE `tf_campaign_cardvoc` (
  `CAMPAIGN_ID` char(20) NOT NULL COMMENT '活动实例ID',
  `SHOW_NO` int(11) NOT NULL COMMENT '展示顺序，从0开始',
  `CARDVOC_TYPE` char(1) NOT NULL COMMENT '卡券品种：1代金券、2项目卡、3储值卡',
  `CARDVOC_TYPE_ID` char(20) NOT NULL COMMENT '卡券品类ID',
  `CARDVOC_TYPE_NAME` varchar(100) NOT NULL COMMENT '卡券品类名称',
  `CARDVOC_MONEY` int(8) NOT NULL COMMENT '卡券面值/价格，单位为分',
  `CARDVOC_CAMPN_STATE` char(1) NOT NULL COMMENT '卡券的销售状态：0无效、1有效',
  `QUANTITY_PERORDER` int(11) NOT NULL COMMENT '每笔订单交付的卡券数量，默认1张',
  `CARDVOC_IMAGE_URL` varchar(256) DEFAULT NULL COMMENT '卡券图片链接',
  `CARDVOC_SLOGAN` varchar(300) DEFAULT NULL COMMENT '卡券宣传语',
  `PRECARD_FEE_STORE` int(11) NOT NULL DEFAULT '0' COMMENT '储值卡充值金额，非储值卡填0',
  `PRECARD_FEE_GRANT` int(11) NOT NULL DEFAULT '0' COMMENT '储储值卡赠送金额，默认0，非储值卡填0',
  `ACTIVATE_TYPE` char(1) NOT NULL COMMENT '激活方式：1立即激活（卡券默认）、2使用时激活（仅项目卡）、3指定激活时间（代金券），默认1，实物商品填0',
  `PERIOD_NUMBER` int(11) DEFAULT NULL COMMENT '代金券有效期天数，激活方式1时使用',
  `ACTIVATE_DATE` datetime DEFAULT NULL COMMENT '代金券有效期激活时间，代金券激活方式3时使用',
  `EXPIRE_DATE` datetime DEFAULT NULL COMMENT '代金券有效期截止时间，代金券激活方式3时使用',
  `OPERATOR_ID` char(20) NOT NULL COMMENT '操作人ID',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`CAMPAIGN_ID`, `CARDVOC_TYPE_ID`, `CARDVOC_TYPE`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动卡券信息表';

CREATE TABLE `tf_campaign_order` (
  `ORDER_ID` char(20) NOT NULL COMMENT '订单ID',
  `USER_ID` char(20) NOT NULL COMMENT '客户ID',
  `CAMPAIGN_ID` char(20) NOT NULL COMMENT '活动ID',
  `ORDER_STATE` char(1) NOT NULL DEFAULT '0' COMMENT '订单状态：0待支付、1已完成、2支付中、3已支付/待发卡、4支付失败、5返销/退款中、6已返销/退款（含部分）、9已取消，默认0',
  `ORDER_DESC` varchar(300) DEFAULT NULL COMMENT '订单描述',
  `ORDER_SCORE` int(11) NOT NULL DEFAULT '0' COMMENT '订单需支付的积分数，下单时填写，默认0',
  `ORDER_CASH` int(11) NOT NULL DEFAULT '0' COMMENT '订单需支付的现金数，单位分，默认0，下单时填写',
  `ORDER_PAY_SCORE` int(11) NOT NULL DEFAULT '0' COMMENT '订单已支付积分数值，初始填0，完成积分扣减后更新',
  `ORDER_PAY_FEE` int(11) NOT NULL DEFAULT '0' COMMENT '订单已付现金，单位：分，默认/初始填0，收款成功后更新',
  `PAY_TIME` datetime DEFAULT NULL COMMENT '完成支付的时间',
  `REFERRER_TYPE` char(1) DEFAULT '2' COMMENT '推荐人类型：1客户、2员工、3第三方，默认2',
  `REFERRER_ID` char(20) DEFAULT NULL COMMENT '推荐人ID，根据操作人类型填写客户ID、或员工ID、或第三方人员标识（如ID、手机号、姓名等）',
  `OPERATOR_TYPE` char(1) NOT NULL DEFAULT '1' COMMENT '操作人类型：1客户、2员工、3第三方，默认1',
  `OPERATOR_ID` varchar(20) DEFAULT NULL COMMENT '操作人ID，根据操作人类型填写客户ID、或员工ID、或第三方人员标识（如ID、手机号、姓名等）',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '订单生成时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间，订单有变更时更新',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ORDER_ID`),
  KEY `IDX_CAMPAIGN_ORDER_UID` (`USER_ID`) USING BTREE,
  KEY `IDX_CAMPAIGN_ORDER_CID` (`CAMPAIGN_ID`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动订单主表';

CREATE TABLE `tf_campaign_order_cardvoc` (
  `ORDER_ID` char(20) NOT NULL COMMENT '订单ID',
  `SHOW_NO` int(11) NOT NULL COMMENT '展示顺序',
  `CARDVOC_TYPE` char(1) NOT NULL COMMENT '卡券品种：1代金券、2项目卡、3储值卡',
  `CARDVOC_TYPE_ID` char(20) NOT NULL COMMENT '卡券品类ID',
  `ORDER_NUM` int(11) NOT NULL COMMENT '订购卡/券数量，默认1',
  `PRECARD_USE_MODE` char(1) NOT NULL COMMENT '储值卡使用模式：1新开卡充值、2续卡充值，储值卡使用，非储值卡填0',
  `PRECARD_ID` varchar(20) DEFAULT NULL COMMENT '储值卡ID，使用模式2时工单生成时填写，1时开卡后填写，储值卡使用，非储值卡留空',
  `PRECARD_FEE_STORE` int(11) NOT NULL COMMENT '储值卡充值金额，非储值卡填0',
  `PRECARD_FEE_GRANT` int(11) NOT NULL COMMENT '储值卡赠送金额，默认0，非储值卡填0',
  `USER_TYPE_CHANGE` char(1) NOT NULL COMMENT '充值时是否变更会员级别：0不变更、1变更，储值卡使用，非储值卡填0',
  `USER_TYPE` char(1) NOT NULL COMMENT '变更时新的会员级别，不变更时填0，储值卡使用，非储值卡填0',
  `SERVCARD_AMOUNT` int(11) NOT NULL COMMENT '订购的服务项目数量，无限次99999999，项目卡使用，非项目卡填0',
  `SERVCARD_GRANT` int(11) NOT NULL DEFAULT '0' COMMENT '购卡赠送次数，默认0，项目卡使用',
  `ACTIVATE_TYPE` char(1) NOT NULL DEFAULT '1' COMMENT '激活方式：1立即激活、2使用时激活、3指定激活时间，默认1',
  `EXPIRE_START_TIME` datetime DEFAULT NULL COMMENT '有效期开始时间，激活方式1、3时使用',
  `EXPIRE_END_TIME` datetime DEFAULT NULL COMMENT '有效期结束时间，激活方式1、3时使用',
  `EXPIRE_TYPE` char(1) NOT NULL DEFAULT '0' COMMENT '卡/券有效期类型：0无限期、1按天、2按周、3按月、4按季度、5按年，默认0，激活方式2时使用',
  `PERIOD_NUMBER` int(11) NOT NULL COMMENT '卡有效期期数，当类型非0时该字段有效，激活方式2时使用',
  `LAST_ACTIVE_DATE` datetime DEFAULT NULL COMMENT '卡最晚激活时间，可空，激活方式2时使用',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  KEY `IDX_CAMPAIGN_ORDER_CARDVOC` (`ORDER_ID`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动订单卡券表';

CREATE TABLE `tf_campaign_order_pay` (
  `ORDER_ID` char(20) NOT NULL COMMENT '订单ID',
  `TRADE_TYPE` char(1) NOT NULL COMMENT '交易类型：1支付、2退款',
  `PAY_TYPE` char(1) NOT NULL COMMENT '客户支付类型：1微信支付',
  `PAY_DEALMODE` char(1) NOT NULL COMMENT '系统处理模式：1系统收款',
  `PAY_FEE` int(11) NOT NULL COMMENT '已收款金额，单位：分',
  `PAYLOG_ID` char(20) NOT NULL COMMENT '收款记录表流水ID，退款记录填写原收款的流水ID',
  `REFUND_FEE` int(11) NOT NULL DEFAULT '0' COMMENT '退款金额，不大于PAY_FEE，单位：分，默认0',
  `REFUNDLOG_ID` varchar(20) DEFAULT NULL COMMENT '退款记录表流水ID，未发生退款的收款记录留空',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  KEY `IDX_CAMPAIGN_ORDER_PAY_OID` (`ORDER_ID`) USING BTREE
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动订单收款/退款表';

CREATE TABLE `tf_campaign_order_worder` (
  `ORDER_ID` char(20) NOT NULL COMMENT '订单ID',
  `WORDER_TYPE` char(1) NOT NULL COMMENT '工单类型：1代金券工单、2项目卡工单',
  `WORDER_ID` char(20) NOT NULL COMMENT '工单ID',
  `TIME_CREATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `TIME_UPDATE` datetime NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
  `REMARK` varchar(1000) DEFAULT NULL COMMENT '备注',
  PRIMARY KEY (`ORDER_ID`, `WORDER_ID`)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '活动订单工单关系表';
